// Drums — generated by @web-kits/audio and refined for this project
// patch: Drums
import type { Layer, SoundDefinition, SoundPatch } from "@web-kits/audio";

export const kick: SoundDefinition = {"source":{"type":"sine","frequency":{"start":150,"end":40}},"envelope":{"attack":0.001,"decay":0.25,"sustain":0,"release":0.1},"gain":0.8};
export const snare: SoundDefinition = {"layers":[{"source":{"type":"noise","color":"white"},"envelope":{"attack":0.001,"decay":0.15,"sustain":0,"release":0.05},"filter":{"type":"highpass","frequency":2000},"gain":0.5},{"source":{"type":"sine","frequency":{"start":200,"end":120}},"envelope":{"attack":0.001,"decay":0.1,"sustain":0,"release":0.05},"gain":0.6}]};
export const hatClosed: SoundDefinition = {"source":{"type":"noise","color":"white"},"envelope":{"attack":0.001,"decay":0.08,"sustain":0,"release":0.03},"filter":{"type":"highpass","frequency":6000},"gain":0.4};
export const hatOpen: SoundDefinition = {"source":{"type":"noise","color":"white"},"envelope":{"attack":0.001,"decay":0.25,"sustain":0,"release":0.1},"filter":{"type":"highpass","frequency":6000},"gain":0.35};
const tomLayer = {"source":{"type":"sine","frequency":{"start":200,"end":80}},"envelope":{"attack":0.001,"decay":0.2,"sustain":0,"release":0.08},"gain":0.6} satisfies Layer;
export const tom: SoundDefinition = tomLayer;

// A fast-to-slow roll made only from copies of the stock Tom definition.
// The final Tom alone gets a subtle feedback delay, leaving a short echo tail.
const TOM_GLYPH_HIT_DELAYS = [0, 0.05, 0.101, 0.154, 0.21, 0.27, 0.338, 0.416, 0.508] as const;
export const tomGlyphRhythm: SoundDefinition = {
  layers: TOM_GLYPH_HIT_DELAYS.map((delay, index) => ({
    ...tomLayer,
    delay,
    ...(index === TOM_GLYPH_HIT_DELAYS.length - 1
      ? { effects: [{ type: "delay" as const, time: 0.18, feedback: 0.24, mix: 0.14 }] }
      : {}),
  })),
};
export const clap: SoundDefinition = {"source":{"type":"noise","color":"white"},"envelope":{"attack":0.001,"decay":0.12,"sustain":0,"release":0.04},"filter":{"type":"bandpass","frequency":2500,"resonance":2},"gain":0.5};
export const rim: SoundDefinition = {"source":{"type":"noise","color":"pink"},"envelope":{"attack":0.001,"decay":0.1,"sustain":0,"release":0.05},"filter":{"type":"bandpass","frequency":3000,"resonance":3},"gain":0.5};
export const shaker: SoundDefinition = {"source":{"type":"noise","color":"white"},"envelope":{"attack":0.005,"decay":0.06,"sustain":0,"release":0.03},"filter":{"type":"highpass","frequency":8000},"gain":0.3};

export const _patch: SoundPatch = {
  ...{"name":"Drums","author":"Raphael Salaja","version":"1.0.0","description":"A rhythm-focused kit of synthesized kicks, snares, hi-hats, and percussive one-shots that adds punch and momentum to micro-interactions, game loops, and dynamic product moments."},
  sounds: { kick, snare, "hat-closed": hatClosed, "hat-open": hatOpen, tom, "tom-glyph-rhythm": tomGlyphRhythm, clap, rim, shaker },
};
